repos:
  - repo: local
    hooks:
      - id: no-print
        name: No print
        description: This hook prevents print function calls
        entry: "print\\((?!.*allow-print)"
        language: pygrep
        types: [python]
        exclude: "cli.py$"
  - repo: https://github.com/ambv/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3.11
  - repo: https://github.com/PyCQA/isort
    rev: v5.11.5
    hooks:
      - id: isort
  - repo: https://github.com/pycqa/pydocstyle
    rev: "6.3.0"
    hooks:
      - id: pydocstyle
        args: ["--add-select=D213,D404", "--ignore=D202,D212,D406,D407,D203"]
        exclude: "^test"
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.2.0
    hooks:
      - id: mypy
        args:
          - --show-error-codes
        exclude: ^test
  - repo: https://github.com/pycqa/pylint
    rev: "v2.17.2"
    hooks:
      - id: pylint
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.7.1"
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: debug-statements
      - id: name-tests-test
        args: ["--django"]
      - id: trailing-whitespace
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.1
    hooks:
      - id: forbid-crlf
      - id: remove-crlf
      - id: forbid-tabs
      - id: remove-tabs
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.6.0
    hooks:
      - id: markdownlint-cli2
        language_version: system
